Algoritmo "IAL002- Exercícios Apostila Logica de Programação - Repetição" 
// Disciplina: [Linguagem e Logica de Programação] 
// Professor: Carmen Lúcia de Bartolo Costa 
// Descrição: EX.01 Gera e escreve os números ímpares entre 100 e 200. 
// Autor(a): Gabriela Nogueira
// Data atual: 18/03/2024
Var
i: inteiro

Inicio
para i de 100 ate 200 faca
	se i % 2 = 1 entao
		escreva (i:3)
	fimse
fimpara
Fimalgoritmo