Algoritmo "IAL002- Exercícios Apostila Logica de Programação - Repetição" 
// Disciplina: [Linguagem e Logica de Programação] 
// Professor: Carmen Lúcia de Bartolo Costa 
// Descrição: Gera e escreve os números pares entre 25 e 78. 
// Autor(a): Gabriela Nogueira
// Data atual: 18/03/2024
Var
i: inteiro

Inicio
para i de 25 ate 78 faca
	se i % 2 = 0 entao
		escreva (i:3)
	fimse
fimpara
Fimalgoritmo
