Algoritmo "IAL002- Exercícios Apostila Logica de Programação - Repetição" 
// Disciplina: [Linguagem e Logica de Programação] 
// Professor: Carmen Lúcia de Bartolo Costa 
// Descrição: EX.01 Gera e escreve os números ímpares entre 100 e 200. 
// Autor(a): Gabriela Nogueira
// Data atual: 18/03/2024
var
s,i:inteiro

Inicio

s <- 0
i <- 1
enquanto (i <= 10) faca
	s <- s + i i <- i + 1
	escreva(i:3)
fimenquanto
escreval (s)

Fimalgoritmo